# Site settings
title: LorDistasteful
email: lorenzoderi314+tees@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I like to design funny t-shirts that I then display proudly.
  If you like them, you can have one too and buy me a beer in the process.
baseurl: "/LorDistasteful"
url: "http://lordisturbia.pw" # the base hostname & protocol for your site
instagram_username: LorDisturbia
github_username: LorDisturbia

# Build settings
markdown: kramdown
permalink: pretty
